
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: labahn-first-heroku-development

test:
  <<: *default
  database: labahn-first-heroku-test

production:
  <<: *default
  database: labahn-first-heroku
